import { useContext, useEffect, useRef } from "react";
import Head from "next/head";
import Overview from "../components/Home/Overview";
import Forecast from "../components/Home/Forecast";
import Loader from "../components/Loader";
import useOnScreen from "../hooks/useOnScreen";
import { LocationContext } from "../contexts/locationContext";
import { WeatherContext } from "../contexts/WeatherContext";
import styles from "../styles/pages/Home.module.scss";

const Home = () => {
    const { location } = useContext(LocationContext);
    const { weather, weatherLoading, fetchWeather } =
        useContext(WeatherContext);

    useEffect(() => {
        location && fetchWeather(location.geometry.lat, location.geometry.lng);
    }, [fetchWeather, location]);
    return (
        <div className={styles.Home}>
            <Head>
                <title>MyWeather</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={"Main " + styles.HomeMain}>
                {location && (!weatherLoading || weather) ? (
                    <>
                        <Overview />
                        <Forecast />
                    </>
                ) : (
                    <div className={styles.LoaderContainer}>
                        <Loader />
                    </div>
                )}
            </main>
        </div>
    );
};

export default Home;
