import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import axios from "axios";
import Overview from "../components/Home/Overview";
import Forecast from "../components/Home/Forecast";
import styles from "../styles/pages/Home.module.scss";

const Home = () => {
    const [location, setLocation] = useState();

    const router = useRouter();

    // Check if localStorage has Location

    useEffect(() => {
        const localStorageLoc = localStorage.getItem("location");
        localStorageLoc || location
            ? setLocation(localStorageLoc)
            : router.push("/landing");
    }, [location, router]);

    // Fetch Weather from NEXT.js API

    useEffect(() => {
        const getWeather = async () => {
            try {
                const res = await axios.get("/api/weather", {
                    params: { lat: location.lat, long: location.long },
                });

                console.log(res);
            } catch (error) {
                console.log(error);
            }
        };

        location && getWeather();
    }, [location]);

    return (
        <div className={styles.Home}>
            <Head>
                <title>MyWeather</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={"Main " + styles.HomeMain}>
                {location ? (
                    <>
                        <Overview />
                        <Forecast />
                    </>
                ) : (
                    <h1>LOADER...</h1>
                )}
            </main>
        </div>
    );
};

export default Home;
