import React from "react";
import Head from "next/head";
import Credits from "../components/Home/Credits";
import LocationPicker from "../components/Landing/LocationPicker";
import styles from "../styles/pages/Landing.module.scss";

const landing = () => {
    return (
        <div className={styles.Landing}>
            <Head>
                <title>MyWeather</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <title>weatherly - Forecast for you 🤍</title>
            </Head>
            <main>
                <LocationPicker />
                <Credits />
            </main>
        </div>
    );
};

export default landing;
